/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package binarysearch;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        binarySearch classUnderTest = new binarySearch();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }


    @Test
    public void binary_search() {
        assertEquals("It should return the index of the search key",0,
                binarySearch.binary_search(new int[] {15, 1, 2}, 15));
        assertEquals("It should return -1 for search key not found in the array",-1, binarySearch.binary_search(new int[]{1, 2, 3}, 15));

    }
}
