/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Data.Structures;


public class LinkedList {


    public  Node head;

    public static void main(String[] args) {
        LinkedList l = new LinkedList();
        l.insert(5);
        l.insert(3);
        l.insert(4);
        l.toString();
    }

    public void  insert(int data){

        if (head==null) {
            Node y = new Node(data);
            y.next = head;
            head = y;
        } else {
            Node k = head;
            while (k.next != null) {
                k = k.next;

            }
            k.next = new Node(data);
        }


    }

    public boolean Includes(int d){
        Node current = this.head;

        while (current.next !=null){
            if (current.data==d){
                return true;

            }
            current=current.next;
        }
        return false;
    }

    public String toString() {
        String msg = " ";
        if (head==null) {
            return null;
        } else {
            while (head != null) {
                msg = msg + "{" + head.data + "}" + " -> ";
                head = head.next;
            }
            msg = msg + "NULL";
            System.out.print(msg);
            return msg;
        }
    }
    }


