/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.and.queue;

import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {




    }


