/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Data.Structures;

import org.junit.Test;
import static org.junit.Assert.*;

public class LinkedListTest {

    @Test
    public void testInsert() {
        LinkedList l = new LinkedList();
        l.insert(5);
        l.insert(3);
        l.insert(4);
        String expected = "{5} -> {3} -> {4} -> NULL";
        assertEquals("the output is", expected, l.toString());
    }

    @Test
    public void test_include_true() {
        LinkedList classUnderTest = new LinkedList();
        classUnderTest.insert(1);
        classUnderTest.insert(1);
        classUnderTest.insert(8);
        assertTrue(classUnderTest.Includes(8));
    }
    @Test
    public void test_include_false() {
        LinkedList classUnderTest = new LinkedList();
        classUnderTest.insert(3);
        classUnderTest.insert(3);
        classUnderTest.insert(3);
        assertFalse(classUnderTest.Includes(4));
    }

}
