/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.and.queue;

public class Library {

        public static void main(String[] args) {

            stack stack = new stack();
            System.out.println(stack.isEmpty());
       stack.push(5);
       stack.push(2);
       stack.push(3);
       System.out.println(stack.peek());

       System.out.println(stack.pop());
       System.out.println(stack.pop());
       System.out.println(stack.pop());

           queue queue = new queue();
           queue.enqueue(2);
           System.out.println(queue);
           System.out.println(queue.dequeue());
           System.out.println(queue);
           System.out.println(queue.isEmpty());
           System.out.println(queue.peek());
           queue.enqueue(2);

           System.out.println(queue.dequeue());

            


    }


